# Generated by Django 5.2.7 on 2025-10-31 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='메시지에 첨부된 이미지 파일', null=True, upload_to='chat_images/')),
                ('is_user', models.BooleanField(default=True)),
                ('character_emotion', models.CharField(blank=True, help_text='AI 캐릭터의 감정 상태', max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PendingProactiveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatbot_app.chatmessage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_proactive_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('all', '랜덤'), ('korean_history', '한국사'), ('world_history', '세계사'), ('science', '과학'), ('literature', '문학'), ('general', '상식')], help_text='퀴즈 장르', max_length=100)),
                ('num_questions', models.IntegerField(help_text='총 문제 수')),
                ('score', models.IntegerField(help_text='획득 점수')),
                ('date_completed', models.DateTimeField(auto_now_add=True, help_text='퀴즈 완료 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_completed'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(blank=True, help_text='활동 날짜', null=True)),
                ('activity_time', models.TimeField(blank=True, help_text='활동 시간', null=True)),
                ('place', models.CharField(blank=True, help_text='장소', max_length=255, null=True)),
                ('companion', models.CharField(blank=True, help_text='동행인', max_length=255, null=True)),
                ('memo', models.TextField(blank=True, help_text='활동 관련 메모 또는 대화 내용', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, help_text='사용자 닉네임', max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='사용자 프로필 사진', null=True, upload_to='profile_pics/')),
                ('is_onboarding_complete', models.BooleanField(default=False, help_text='사용자 초기 설정(온보딩) 완료 여부')),
                ('affinity_score', models.IntegerField(default=0, help_text="AI '아이'와의 호감도 점수")),
                ('memory', models.JSONField(default=dict, help_text='사용자에 대한 기억 저장소')),
                ('chatbot_name', models.CharField(default='아이', help_text='사용자가 지정한 챗봇 이름', max_length=100)),
                ('persona_preference', models.CharField(default='친근한', help_text='챗봇의 스타일', max_length=100)),
                ('status_message', models.CharField(blank=True, help_text='사용자 상태 메시지', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='일과 날짜')),
                ('schedule_time', models.TimeField(blank=True, help_text='일과 시간', null=True)),
                ('content', models.TextField(blank=True, help_text='하루 일과 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', '-schedule_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', '주간'), ('monthly', '월간'), ('yearly', '연간')], max_length=10)),
                ('period_start_date', models.DateField(help_text='통계 기간의 시작일')),
                ('place', models.CharField(db_index=True, help_text='장소', max_length=255)),
                ('companion', models.CharField(blank=True, db_index=True, help_text='동행인', max_length=255, null=True)),
                ('count', models.PositiveIntegerField(default=0, help_text='해당 기간 동안의 방문 횟수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'period_type', 'period_start_date', 'place', 'companion')},
            },
        ),
        migrations.CreateModel(
            name='FriendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_chatbot_name', models.CharField(help_text='보낸 사람 챗봇 이름', max_length=100)),
                ('sender_persona', models.CharField(help_text='보낸 사람 챗봇 페르소나', max_length=100)),
                ('message_content', models.TextField(help_text='쪽지 내용')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['receiver', 'is_read'], name='chatbot_app_receive_aae096_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_type', models.CharField(blank=True, help_text="속성의 종류 (예: '성격', 'MBTI', '생일')", max_length=100, null=True)),
                ('content', models.CharField(blank=True, help_text="속성 내용 (예: '털털함', 'INFP', '1995-10-31')", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'fact_type', 'content')},
            },
        ),
        migrations.CreateModel(
            name='UserFriendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '대기 중'), (2, '친구')], default=1)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_code', models.UUIDField(default=uuid.uuid4, editable=False, help_text='동일 인물 구분을 위한 고유 시리얼 코드', unique=True)),
                ('relationship_type', models.CharField(help_text='관계 유형 (예: 가족, 친구, 직장 동료)', max_length=100)),
                ('position', models.CharField(blank=True, help_text='관계 내 포지션 (예: 오빠, 친한 친구, 상사)', max_length=100, null=True)),
                ('name', models.CharField(help_text='상대방 이름', max_length=100)),
                ('disambiguator', models.CharField(blank=True, help_text="동명이인 구분을 위한 식별자 (예: '개발팀', '친구')", max_length=100, null=True)),
                ('traits', models.TextField(blank=True, help_text='상대방 성격 또는 특징', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'serial_code')},
            },
        ),
    ]
